//! Install jj-prek hooks into a jj workspace.
//!
//! Since jj does not have a `.git/hooks` directory, installation works by
//! configuring a jj alias that runs `jj-prek` before commit operations.
//!
//! Two installation modes:
//!   1. **jj config alias** — adds `jj prek` alias via `jj config set`
//!   2. **Shell wrapper** — creates a shell script in the workspace

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use owo_colors::OwoColorize;

use crate::config;
use crate::jj;
use crate::printer::Printer;
use crate::run::ExitStatus;

/// Install jj-prek into the workspace.
///
/// Creates a hook script at `.jj/hooks/pre-commit` and configures a jj alias.
#[allow(clippy::print_stdout)]
pub(crate) fn install(
    config_path: Option<&PathBuf>,
    overwrite: bool,
    printer: Printer,
) -> Result<ExitStatus> {
    let root = jj::JJ_ROOT
        .as_ref()
        .map_err(|e| anyhow::anyhow!("Not in a jj workspace: {e}"))?;

    // Verify config exists
    let found_config = config_path.cloned().or_else(|| config::find_config(root));

    if found_config.is_none() {
        println!(
            "{} No config file found. Run `jj-prek init` first to create one.",
            "Warning:".yellow().bold()
        );
    }

    let jj_prek_bin = std::env::current_exe().context("Failed to find jj-prek binary path")?;
    let jj_prek_bin_str = jj_prek_bin.to_string_lossy();

    // Create the hooks directory
    let hooks_dir = root.join(".jj").join("hooks");
    std::fs::create_dir_all(&hooks_dir)
        .context("Failed to create .jj/hooks directory")?;

    // Create the pre-commit hook script
    let hook_path = hooks_dir.join("pre-commit");

    if hook_path.exists() && !overwrite {
        if is_our_script(&hook_path)? {
            println!(
                "{} jj-prek is already installed at `{}`",
                "Info:".cyan().bold(),
                hook_path.display()
            );
            return Ok(ExitStatus::Success);
        }
        println!(
            "{} Hook already exists at `{}`. Use --overwrite to replace it.",
            "Error:".red().bold(),
            hook_path.display()
        );
        return Ok(ExitStatus::Failure);
    }

    let mut config_arg = String::new();
    if let Some(cfg) = config_path {
        write!(config_arg, " --config \"{}\"", cfg.display())?;
    }

    let hook_script = format!(
        r#"#!/bin/sh
# File generated by jj-prek: https://github.com/MarkMarine/prek
# ID: jj-prek-hook-v1

JJ_PREK="{jj_prek_bin_str}"

# Check if the full path to jj-prek is executable, otherwise fallback to PATH
if [ ! -x "$JJ_PREK" ]; then
    JJ_PREK="jj-prek"
fi

exec "$JJ_PREK"{config_arg} "$@"
"#
    );

    std::fs::write(&hook_path, &hook_script)
        .with_context(|| format!("Failed to write hook script: {}", hook_path.display()))?;

    // Make executable on Unix
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = hook_path.metadata()?.permissions();
        perms.set_mode(0o755);
        std::fs::set_permissions(&hook_path, perms)?;
    }

    if !printer.is_silent() {
        println!(
            "{} Installed jj-prek hook at `{}`",
            "Success:".green().bold(),
            hook_path.display().cyan()
        );
        println!();
        println!("You can now run hooks with:");
        println!("  {} - run on working copy changes (default)", "jj-prek".cyan());
        println!("  {} - run on all tracked files", "jj-prek --all-files".cyan());
        println!(
            "  {} - run on last committed change",
            "jj-prek --last-change".cyan()
        );
        println!();
        println!("To run automatically, add to your jj config:");
        println!(
            "  {}",
            format!(
                "[aliases]\nprek = [\"util\", \"exec\", \"--\", \"{jj_prek_bin_str}\"]"
            )
            .dimmed()
        );
    }

    Ok(ExitStatus::Success)
}

/// Uninstall jj-prek from the workspace.
#[allow(clippy::print_stdout)]
pub(crate) fn uninstall(printer: Printer) -> Result<ExitStatus> {
    let root = jj::JJ_ROOT
        .as_ref()
        .map_err(|e| anyhow::anyhow!("Not in a jj workspace: {e}"))?;

    let hook_path = root.join(".jj").join("hooks").join("pre-commit");

    if !hook_path.exists() {
        if !printer.is_silent() {
            println!("{} No jj-prek hook found to uninstall.", "Info:".cyan().bold());
        }
        return Ok(ExitStatus::Success);
    }

    if !is_our_script(&hook_path)? {
        println!(
            "{} `{}` is not a jj-prek hook, skipping.",
            "Warning:".yellow().bold(),
            hook_path.display()
        );
        return Ok(ExitStatus::Failure);
    }

    std::fs::remove_file(&hook_path)?;

    if !printer.is_silent() {
        println!(
            "{} Uninstalled jj-prek hook from `{}`",
            "Success:".green().bold(),
            hook_path.display().cyan()
        );
    }

    Ok(ExitStatus::Success)
}

static CURRENT_HASH: &str = "jj-prek-hook-v1";

/// Check if a hook script was created by jj-prek.
fn is_our_script(path: &Path) -> Result<bool> {
    let content = std::fs::read_to_string(path)
        .with_context(|| format!("Failed to read hook: {}", path.display()))?;
    Ok(content.contains(CURRENT_HASH))
}
